### ISSUE TITLE
1.16.5 crash on shulker missile hit

### ISSUE THREAD

**Issue by superon** [SFort/MC-SurvivalFlight#14]
the shulker missile hit maybe just coincidence:

i've been experiencing this whilst flying
snippet of log maybe highlighting some issue here:
https://pastebin.com/vEuKugfH

also here's the latest crashlog:
https://pastebin.com/KGBtx8hm

and the creative_flight.script:
https://pastebin.com/b3YxTKex

it doesn't crash every time but has been crashing pretty consistently when flying whilst being hit by a load of them within about 10 minutes.
not sure survival flight is indeed the cause of the crash though it seems to only happen when this is enabled

**Comment by SFort** [comment]
so here's what's happening as i understand it.:
a new subtitle is being added while the game is rendering the previous ones.

you can probably just disable subtitles if that's an option for you.
otherwise this is probably caused by some mod that is either directly adding subtitles when it shouldn't.
or playing sounds on a thread it shouldn't.
best of luck finding out what, i'm pretty certain this is unrelated to survival flight though

**Comment by SFort** [comment]
since you say it only happens with survival flight. it might be caused by a mod that improperly adds a flight sound?
