### ISSUE TITLE
What to write in creative_flight script file??????

### ISSUE THREAD

**Issue by OUTofFIRE** [SFort/MC-SurvivalFlight#23]
i tried so many things. in that file, if i write something else than juts false, i have creative flight in game. I know nothing about coding, and "simpler" version you did didn't help me at all.

Call you tell me exactly what to write into that file...

cause i tried:

false

chest: elytra

or tried:

false

chest: elytra

and same with 
[chest: item.minecraft.elytra]  or !chest: item.minecraft.elytra or (chest: item.minecraft.elytra)

and unfortunately nothing is working.

Plz, what document i have to modify ( I presume ONLY the creative_flight.script), and what I need to write exactly in it?

All i wanna do, is having creative flight ONLY when i am wearing elytra.

Thank you in advance for your work, and for your time to answer!

**Comment by OUTofFIRE** [comment]
i dont know why it put BOLD BIG LETTERS, sorry for that.

**Comment by SFort** [comment]
feel free to take a look at the script file after to see what is inside.
if you're running a server you'll also need to copy the script to it since the UI is client only.

(since you can't see my mouse in the video just make sure to click the `chest` without the ~ and make sure to click save when you're done)

https://user-images.githubusercontent.com/1879846/235615544-a43ee720-fe19-47a9-96ae-cb4dca55c37c.mp4

**Comment by OUTofFIRE** [comment]
Thank you for the quick response!! Yes it is on a server, so i loaded the mod into singleplayer to try (as you did on video i think)

So all i had to do was (in the creative_flight.script) delete "false" and only write: "chest:minecraft:elytra" (without the "")

All is working now, thank you so much!!!
