### ISSUE TITLE
[Feature Suggestion] Enable flight only for beacons of specific blocks

### ISSUE THREAD

**Issue by Nick-Brutschy** [SFort/MC-SurvivalFlight#26]
What I would really love as a feature for this mod is the ability to only allow survival flight for players if they are within beacon range *and* the beacon is of a certain block (for example: only grant flight if the base is made of netherite blocks). If you could add this feature it would be much appreciated!

**Comment by SFort** [comment]
If you really really want this i'm fine making a one off version that has it but it's not getting released outside of this gh issue and i will not port it.
I'll also probably just rip the code from better beacons so it'll be incompatible with it.
 so if you're fine with that just tell me the version

but i'm not adding it to the main version just because i really don't want to maintain that feature

**Comment by Nick-Brutschy** [comment]
I would greatly appreciate this. I use 1.20.1 (if this is what you mean by version). Also, do you have a place I can donate to you? I'm a college student and I also have no idea how much effort doing something like this requires on your part but I'd like to compensate what I am able if you are alright with going through and making this.

**Comment by SFort** [comment]
there i've transfered the repo with the mod.
make it public if you like.
donation wise the only thing i take is amazon.de gift cards, you could email em to me i guess? (mostly use em to donate to others) but it's fine.
effort wise it was thrown together in about an hour.... the appended vid is litterally all the testing i did sooo +1minute of testing.
hope it's not too jank, best of luck with it.

EDIT: forgot to mention what the mod does it adds: `nick_beacon`, `nick_beacon_delayed`, `nick_beacon_level` and `nick_beacon_level_delayed`, you can easily enough rename the conditions by changing them in `src/main/java/tf/ssf/sfort/nicks_beacon_block_fscript_addon/FlightScript.java`

and since it's a fscript addon it'll also work for Fabrication (untill mojang updates it outa existance at least ;p)

https://github.com/SFort/MC-SurvivalFlight/assets/1879846/1b053d62-ce4b-40a4-84ef-81bb5cacee7e

**Comment by Nick-Brutschy** [comment]
Thank you for your work!! I downloaded the jar file and fscript but I am
having a little trouble getting things to work. I see that there are
various config files in config > survival flight, and I see the bit in
script_help but I am unclear where I actually change these variables. Could
you please clarify which config I change and the syntax I need to input for
a Netherite_Block? Thank you again!

**Comment by SFort** [comment]
you can just put `nick_beacon:netherite_block` inside `.minecraft/config/SurvivalFlight/creative_flight.script`
in case you want more conditions / are just curious how it works, you can look at #9

**Comment by SFort** [comment]
i've also edited the previous message with the other conditions available, dunno if you get an email for edits
