### ISSUE TITLE
how do i use  this mod

### ISSUE THREAD

**Issue by adrianku10** [SFort/MC-SurvivalFlight#9]
can you explain to me how does this mod work please i dont know anything about scripting

**Comment by SFort** [comment]
this was made to be super simple without having to know any programming stuff. so it's barely even considered scripting.

for super basic example you can just take this [BeaconFlight](https://github.com/ExtraCrafTX/BeaconFlight#example) config.
I hope there's nothing confusing about BeaconFlights config.
that config translated to SurvivalFlight looks like this:

```
[
beacon;
hand: minecraft:feather;
offhand: minecraft:feather;
head: minecraft:diamond_helmet;
chest: minecraft:diamond_chestplate;
legs: minecraft:diamond_leggings;
boots: minecraft:diamond_boots;
advancement: minecraft:end/elytra;
advancement: minecraft:nether/return_to_sender;
]
```

the diffrance being that if you don't want a option instead of listing `value:null` you just don't add the condition at all.

once you understand that you should lern the following
if we switch the brackets from `[]` to `()` like so:

```
(
beacon;
hand: minecraft:feather;
offhand: minecraft:feather;
head: minecraft:diamond_helmet;
chest: minecraft:diamond_chestplate;
legs: minecraft:diamond_leggings;
boots: minecraft:diamond_boots;
advancement: minecraft:end/elytra;
advancement: minecraft:nether/return_to_sender;
)
```

now instead of requirering ALL those things to fly you require at least one. so having ANY allows flight.

after that it's important to note that you can combine these brackets to get slightly more complex situtations

so for example if i wanted all of those conditions but either achivement was fine i could do this:

```
[
beacon;
hand: minecraft:feather;
offhand: minecraft:feather;
head: minecraft:diamond_helmet;
chest: minecraft:diamond_chestplate;
legs: minecraft:diamond_leggings;
boots: minecraft:diamond_boots;
(
  advancement: minecraft:end/elytra;
  advancement: minecraft:nether/return_to_sender;
);
]
```

and the last thing to learn is BeaconFlight could only go as far as `hand:feather` while in SurvivalFlight you can be more specific with
```
[
~hand:[
  enchant:sharpness;
  item:iron_sword
]
]
```
which requires an iron_sword with sharpness
all of the conditions can also be inverted so if we wanted to forbid holding a iron sword with sharpness we put a `!` infront of the condition:
```
[
!~hand:[
  enchant:sharpness;
  item:iron_sword
]
]
```

That's all there is to it logic wise!
As for all the availible conditions i recommend you use the in game scripting menu as it will give you all of them in a easy to understand list.
I hope all this is simple enough, but if you'd like a super simple basic config you can just use it like shown in the first example.

**Comment by adrianku10** [comment]
thanks  bro

**Comment by SFort** [comment]
happy to help, ask if anything else is unclear.

**Comment by Jayjoe4** [comment]
This will help, thanks

**Comment by Artha-Demon** [comment]
Is there a way to have this not disable flight provided by flying mobs with the Identity mod? I have Identity installed, and Survival Flight where I can fly once I acquire an elytra and equip it, but having it installed disables flight if I turn into a blaze, bat, allay, or other flying mob

**Comment by SFort** [comment]
@Artha-Demon 
> Identity mod conflict

- open the [Identity issue tracker](https://github.com/Draylar/identity/issues/new/choose)
- Due to conflicts ask them to add support for https://github.com/Ladysnake/PlayerAbilityLib
- Also referance existing issues, that are related so : issue 536, probably 593 aswell
- Make sure PlayerAbilityLib compat is enabled in survival flights configs
- Install PlayerAbilityLib

p.s.
please open an issue for future questions and not just tack it onto an existing one.
as comenting on existing and unrelated issues notifies everyone involved in the old issue and opening a new one won't
